version: "3"

services:
  postgres:
    restart: unless-stopped
    image:  postgres:9.6.5
    volumes:
      - "postgres_datadir:/var/lib/postgresql/data"
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    ports:
    - "5000:8080"
    depends_on:
    - "postgres"
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/btcpayserver${NBITCOIN_NETWORK:-regtest}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
    postgres_datadir: